# Don't print a new line at the start of the prompt
add_newline = false

format="[fabris](bold blue) [ ](bold purple) [at](bold yellow) $all"

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[->](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[ ](bold bright-red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[nodejs]
format = "via [ $version](bold green) "

[package]
disabled = true
